dist: xenial
language: python
python:
    - "3.5"
    - "3.6"
before_install:
    - sudo apt-get update
    - sudo apt-get install -y libgmp-dev libmpfr-dev libmpc-dev libffi-dev build-essential python3-pip python3-dev python3-dbus libdbus-1-dev libdbus-glib-1-dev
    - pip install coveralls
script: coverage run -m unittest -v
after_success:
    - coveralls
