language: python
matrix:
    include:
        - os: linux
          python: 3.5
        - os: linux
          python: 3.6
        - os: linux
          dist: xenial
          python: 3.7

before_install:
    - ./.travis/install.sh
script:
    - flake8 homekit
    - coverage run -m unittest -v
after_success:
- coveralls
