dist: xenial
language: python
python:
    - "3.5"
    - "3.6"
before_install:
    - sudo apt-get update
    - pip install coveralls
    - pip install flake8
script:
    - flake8 homekit
    - coverage run -m unittest -v
after_success:
    - coveralls
