dist: xenial
language: python
python:
    - "3.3"
    - "3.5"
    - "3.6"
before_install:
    - sudo apt-get update
    - sudo apt-get install -y build-essential python3-dev libdbus-1-dev libdbus-glib-1-dev libgirepository1.0-dev
    - pip install coveralls
    - pip install flake8
script:
    - flake8 homekit
    - coverage run -m unittest -v
after_success:
    - coveralls
