language: python
matrix:
    include:
        - os: linux
          dist: xenial
          python: 3.5
        - os: linux
          dist: xenial
          python: 3.6
        - os: linux
          dist: xenial
          python: 3.7
        - os: osx
          language: generic
          addons:
            homebrew:
              packages: python

install:
- python3 -m venv ./venv
- source venv/bin/activate
- python -m pip install -r requirements.txt -e .
- python -m pip install coveralls

script:
- python -m flake8 homekit
- python -m coverage run -m pytest tests/

after_success:
- coveralls
